### ISSUE TITLE
More NCM examples

### ISSUE THREAD

**Issue by caleb-hamilton** [numericalalgorithmsgroup/NAGPythonExamples#11]
Examples for Mark 27 NCM routines please
- nagf_correg_corrmat_nearest_rank
- nagf_correg_corrmat_fixed

and also a SDP example of solving a NCM problem ?

**Comment by mikecroucher** [comment]
Hi Caleb

There is a corrmat_fixed example in 

http://localhost:8881/notebooks/neareast_correlation_matrices/ncm_poster.ipynb

which compares how the various routines scale and how they affect the matrix.  
See Tests 1 and 2 for the scaling curves.
