### ISSUE TITLE
Example Required: Unscented Kalman Filter

### ISSUE THREAD

**Issue by mikecroucher** [numericalalgorithmsgroup/NAGPythonExamples#2]
NAG currently has this document: https://www.nag.co.uk/industryarticles/unscentedkalman.pdf 

Requirements: 

* [ ] - Simple Python example showing how to call the routines in the basic case
* [ ] - A notebook based on the above document

**Comment by mtowara** [comment]
Link 404s
Unlikely this will be picked up anytime soon
