### ISSUE TITLE
Example Required: Inhomogeneous Time series 

### ISSUE THREAD

**Issue by mikecroucher** [numericalalgorithmsgroup/NAGPythonExamples#3]
NAG currently has this: https://www.nag.co.uk/industryarticles/inhomogeneous_time_series.pdf 

Requirements:
* [x] - Simple Python example showing how to call the routines
* [ ] - A more detailed example notebook that tells a story.  Similar to the above pdf perhaps but with code and data

**Comment by caleb-hamilton** [comment]
I've tried to knock out the first one. Pull request: [here](https://github.com/numericalalgorithmsgroup/NAGPythonExamples/pull/14#issue-396651137)

**Comment by HamptonMarigold** [comment]
Perhaps send Mike C a one liner by teams…. To see if he can take a look

**Comment by HamptonMarigold** [comment]
John Holden would like to recall the message, "[numericalalgorithmsgroup/NAGPythonExamples] Example Required: Inhomogeneous Time series  (#3)".

Disclaimer

The Numerical Algorithms Group Ltd is a company registered in England and Wales with company number 1249803. The registered office is:
Wilkinson House, Jordan Hill Road, Oxford OX2 8DR, United Kingdom.

This e-mail has been scanned for all viruses and malware, and may have been automatically archived by Mimecast Ltd, an innovator in Software as a Service (SaaS) for business.
